name: Java Upgrade Workflow

on:
  push:
    branches:
      - 'wkflow-test'
  pull_request:
    branches:
      - 'wkflow-test'

jobs:
  java-upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Update Java version in pom.xml
        run: |
          sed -i 's/<java.version>1.8<\/java.version>/<java.version>17<\/java.version>/g' pom.xml
          
      - name: Update Java version in build.gradle
        run: |
          sed -i 's/sourceCompatibility = 1.8/sourceCompatibility = 17/g' build.gradle
          sed -i 's/targetCompatibility = 1.8/targetCompatibility = 17/g' build.gradle
          
      - name: Update Dockerfile to use Java 17
        run: |
          sed -i 's/FROM maven:3.6.1-amazoncorretto-8/FROM maven:3.8.6-amazoncorretto-17/g' Dockerfile
          
      - name: Build with Maven
        run: mvn clean package -DskipTests
        
      - name: Run tests
        run: mvn test
        
      - name: Build with Gradle
        run: ./gradlew build -x test
        
      - name: Create summary
        run: |
          echo "## Java Upgrade Summary" >> $GITHUB_STEP_SUMMARY
          echo "✅ Updated pom.xml to Java 17" >> $GITHUB_STEP_SUMMARY
          echo "✅ Updated build.gradle to Java 17" >> $GITHUB_STEP_SUMMARY
          echo "✅ Updated Dockerfile to use Java 17" >> $GITHUB_STEP_SUMMARY
          echo "✅ Verified build with Maven" >> $GITHUB_STEP_SUMMARY
          echo "✅ Verified tests with Maven" >> $GITHUB_STEP_SUMMARY
          echo "✅ Verified build with Gradle" >> $GITHUB_STEP_SUMMARY